# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Lyricsmashup.Repo.insert!(%Lyricsmashup.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.
alias Lyricsmashup.Repo
alias Lyricsmashup.Markov.Song

unless Repo.get(Song, 1) do
  %Song{
    title: "Come together, right now I was from a gun, see",
    lyrics: "<div id=\"lyricsResult\"><h1 class=\"has-text-primary\">Come together, right now I was from a gun, see</h1><div>Now they smile like pigs in a dream</div><div>Ah look at all the way she keeps in deam</div><div>Ah look at all right now it be let her</div><div>Shoot me like Lucy in a naughty girl you can tell you can start to be defer</div><div><br></div><div>By the night when I believe in an answer let it</div><div>Shoot me and somebody spoke and though they are he got Ono sideboard he one fit</div><div>And I can feel his world upon the holes it</div><div>All the way downstairs and I long for though the dirt from a car fit</div><div><br></div><div>It's all right now I can tell you can tell you have found my head</div><div>Shoot me and get a fool who made the lonely people read</div><div>I don't make it better better better na na</div><div>Love was from his socks in the sun here law</div><div><br></div><div>I can start to be an answer let it</div><div>Into the egg man you were made the light of darkness she had to hide away fit</div><div>Writing the movement you on a serviceable Villain as duteous to make it</div><div>Come together yeah yeah let it comes the egg man Now go fit</div><div><br></div><div>I can feel his armchair you can tell you can tell you should have found my troubles seemed so hard to leave her</div><div>Na Take these broken wings and let it in defer</div><div>What does he blew his socks in the holes in</div><div>Little darling it's just won the lonely people begin</div><div><br></div><div>Shoot me and let it in the sound of her</div><div>Speaking words of the lonely people Ah look at all defer</div><div>Found her now go and make it seems like pigs from the egg man they fly</div><div>Then you know you hey Jude Jude Jude Jude lie</div>",
    img_url: "https://picsum.photos/id/108/2000/1333"
  } |> Repo.insert!

  %Song{
    title: "So many words for you, yeah",
    lyrics: "<div id=\"lyricsResult\"><h1 class=\"has-text-primary\">So many words for you, yeah</h1><div>But a hell of love me why can't win this the only</div><div>Tell me the feeling I the day I got lonely</div><div>That way to walk with the one knows</div><div>I wanna hear you in a life goes on rose</div><div><br></div><div>Brothers sisters everybody yeah yeah yeah yeah yeah yeah</div><div>'Cause we are my heart breaking my head pah</div><div>'Cause it's the things I've done all there where you're from</div><div>Baby don't bother calling church doors open wide become</div><div><br></div><div>But the things I've tried to do it is</div><div>God your body right where you're from my God your every minute it riz</div><div>'Cause I say oh yeah yeah yeah yeah yeah</div><div>Ain't no place ain't nothing but now we're back pah</div><div><br></div><div>What are who you did as sure as long as your body</div><div>It goin' on my heart breaking my heart that way embody</div><div>So that kind of love me as long as long as you</div><div>I played my heart that hallelujah shoot right where you're from what to</div><div><br></div><div>Yes I wanna play the city the beach in your mama and where you're a girl like</div><div>They never say don't go breaking my eyes of you strike</div><div>Show me why can't be the beach in my heart</div><div>Can't I want it that way to hide no art</div><div><br></div><div>There ain't nothing but a hell of person</div><div>As you how can save me the chances What you worsen</div><div>Who can save me doing in a life goes on</div><div>And me why I never gonna run dry never say upon</div>",
    img_url: "https://picsum.photos/id/1016/3844/2563"
  } |> Repo.insert!

  %Song{
    title: "And in a part of the sky",
    lyrics: "<div id=\"lyricsResult\"><h1 class=\"has-text-primary\">And in a part of the sky</h1><div>Check on TV last stop is turning back at the driver Say it feels so do</div><div>Every trick I got a leaf\" Why 'cause I can't get that to</div><div>Sometimes I crash my shades well you're known as we do</div><div>I hope they cannot penetrate what I'm burning like fire to</div><div><br></div><div>'Cause you're the list down today on the shower Does live in indiscreet disguise</div><div>Burning like to see if I'm gonna spread the great lakes arise</div><div>My sister that she's an argument Because then you individually on</div><div>A club sandwich once let's form a roommate I like fire upon</div><div><br></div><div>And you take me girl now my friend a trailer so she would read it Which is what if Q and redWe roamed a friend and Yesterday</div><div>I was younger\" Every picture is extremely proud to save the club then day</div><div>Taking me higher burning like fire yeah yeah</div><div>Higher burning like if you really fucked up It's the airport About frilly toothpicks I'm like \"Hey man I think of my friend asked me pah</div><div><br></div><div>Last week I watch the spontaneity that shit's no ending</div><div>You made it but I can't wait to present Mitch Hedberg condescending</div><div>It a letter using a free key duplication laughs That didn't work but I got into a picture is ridiculous That's extra scary to tell my shades well down</div><div>But with 3 pieces of these jokes that I can't wait to our own fairy tale around</div><div><br></div><div>If he says “What” But with my mind on</div><div>Takin' me a picture of it in in indiscreet disguise upon</div><div>And miles of these jokes before Ha ha but really it’s just lost your wallet it's very dangerous to rise</div><div>I fucked up cuz I'm gonna go shave too' arise</div><div><br></div><div>A guy said Hey man can I don't have</div><div>I saw you lost my mind on a CD calve</div><div>Cold hot air balloonLeave your anger in the alphabet would look like if I can't get enough</div><div>Sprawled out and that's not in a whole CD tough</div>",
    img_url: "https://picsum.photos/id/1006/3000/2000"
  } |> Repo.insert!

  %Song{
    title: "And medicine you how the sea",
    lyrics: "<div id=\"lyricsResult\"><h1 class=\"has-text-primary\">And medicine you how the sea</h1><div>And over we break we'll wait until she will fold and in the life</div><div>Up and when you left beneath Christmas trees in holy water strife</div><div>And across a lie that made fetuses with others</div><div>What a burning apartment building 14 stories high druthers</div><div><br></div><div>I sank into a little boy used to leave</div><div>Thunderous sparks that you built a moon across the screen naive</div><div>And when I can hear where their faces filled with you</div><div>Everything that sparkle all the drugs that just lay there in their climb to</div><div><br></div><div>And be placing fingers through your mom would dream</div><div>Daddy please hear where you wanna say what you deam</div><div>And where you could love worth living for two</div><div>Now your head filled with flesh licking ladies to</div><div><br></div><div>Make those wings in milk and the pornographic page</div><div>I will be laughing with all the morning paper blow gauge</div><div>Any love worth living for me fifty years later</div><div>And hang for comforting things in your father made for coordinator</div><div><br></div><div>Standing on down and bend all you take you</div><div>Everything I can see we used to keep it close and they'll be to</div><div>Say what a nice cliff to be laughing with everyone</div><div>They buried her eyes ain't moving now she will spit until the morning run</div><div><br></div><div>And spring and one you and always heading towards</div><div>And your brothers were the whole world began to me records</div><div>They know all when her face on your mother were reaching</div><div>Any love you lose your enemies are awaiting teaching</div>",
    img_url: "https://picsum.photos/id/1066/2144/1424",
    num_likes: 3
  } |> Repo.insert!

  %Song{
    title: "Don't push me close to me",
    lyrics: "<div id=\"lyricsResult\"><h1 class=\"has-text-primary\">Don't push me close to me</h1><div>And the edge Don't you and how I need</div><div>A new day it's a new life for our hopes and expectations read</div><div>Glaciers melting in the people who care if it's a new life</div><div>To me mercy from the end of madness is a fucking psycho strife</div><div><br></div><div>I live or die just madness is gone</div><div>And a new dawn it's a fucking psycho killer on</div><div>A psycho killer Say I'm a psycho killer</div><div>Is it will not to devour my command pillar</div><div><br></div><div>I'm gonna break you do you know how I was a pussy I have to make you</div><div>You know how I must fight for our hopes and I am a fucking psycho to</div><div>Don't push me get off the truth around our rights</div><div>Into the Sun in the Sun in my soul lights</div><div><br></div><div>I've fallen on my plug in the sky you</div><div>Never let me now I live or is done to</div><div>Don't push me close to unify and expectations</div><div>Mercy from the ghosts and a new dawn it's worth it out no congratulations</div><div><br></div><div>I won't be afraid to forget your thresholds</div><div>I'm falling behind now it's worth it out no holds</div><div>They will stop me get off the sea you</div><div>Far away from the powers that their time's coming to feel to</div><div><br></div><div>The truth around our hopes and you set my back's up to the people who care</div><div>Help me I've seen the ground Don't push me bear</div><div>Don't push me get off the men in baby</div><div>You a bold World just to keep the game I will break out maybe</div>",
    img_url: "https://picsum.photos/id/1050/6000/4000",
    num_likes: 6
  } |> Repo.insert!
end
